targetNamespace: ""
parameters: {}
packages:
  - name: databasesCon
    environment:
      PG_DATABASE: "${PG_DATABASE}"
      PG_PORT: "${PG_PORT}"
      PG_USER: "${PG_USER}"
      PG_PASSWORD: "${PG_PASSWORD}"
      PG_HOST: "${PG_HOST}"

    parameters: {}
    annotations: {}
    actions:
      - name: helloPg
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
