targetNamespace: ""
parameters: {}
packages:
  - name: databasesCon
    environment: {}
    parameters: {}
    annotations: {}
    actions:
      - name: helloPg
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: true
        parameters: {}
        annotations: {}
        limits:
          timeout: 5000
          memory: 256
environment:
  PG_HOST: ${PG_HOST}
  PG_DATABASE: ${PG_DATABASE}
  PG_PORT: ${PG_PORT}
  PG_USER: ${PG_USER}
  PG_PASSWORD: ${PG_PASSWORD}
