targetNamespace: ""
parameters: {}
packages:
  - name: databasesCon
    environment: PG_DATABASE:"${PG_DATABASE}"
    parameters: {}
    annotations: {}
    actions:
      - name: helloPg
        binary: false
        main: ""
        runtime: "nodejs:default"
        web: true
        parameters: {}
        environment: {}
        annotations: {}
        limits: {}
